drop table if exists entries;

create table entries(
	id integer primary key autoincrement,
	title text not null,
    time text not null,
    etime text not null,
    text text not null,
    score integer not null,
    username text not null,
    forum integer not null
);

create table staged(
	id integer primary key autoincrement,
	title text not null,
    time text not null,
    etime text not null,
    text text not null,
    score integer not null,
    username text not null,
    forum integer not null
);

create table deleted(
	id integer primary key autoincrement,
	title text not null,
    time text not null,
    etime text not null,
    text text not null,
    score integer not null,
    username text not null,
    forum integer not null
);
create table accounts(
    id integer primary key autoincrement,
	username text not null,
    password text not null,
    teamemail text null,
    admin text not null,
    score integer not null,
    bio text null,
    logo text null,
    school text not null,
    postcode text not null,
    lat text null,
    lng text null,
    teachername text null,
    teacheremail text null,
    geocode text null,
    name1 text not null,
    name2 text  null,
    name3 text  null,
    name4 text  null,
    name5 text  null,
    age1 int not null,
    age2 int  null,
    age3 int  null,
    age4 int  null,
    age5 int null,
    gender1 text null,
    gender2 text null,
    gender3 text null,
    gender4 text null,
    gender5 text null,
    year1 text null,
    year2 text null,
    year3 text null,
    year4 text null,
    year5 text null,
    phys1 int null,
    phys2 int null,
    phys3 int null,
    phys4 int null,
    phys5 int null,    
    physRate1 int null,
    physRate2 int null,
    physRate3 int null,
    physRate4 int null,
    physRate5 int null,
    sciRate1 int null,
    sciRate2 int null,
    sciRate3 int null,
    sciRate4 int null,
    sciRate5 int null,
    sciWords1 int null,
    sciWords2 int null,
    sciWords3 int null,
    sciWords4 int null,
    sciWords5 int null
);
create table req_accounts(
    id integer primary key autoincrement,
    username text not null,
    password text not null,
    teamemail text  null,
    school text not null,
    postcode text  null,
    teachername text  null,
    teacheremail text  null,
    name1 text not null,
    name2 text null,
    name3 text  null,
    name4 text  null,
    name5 text  null,
    age1 int not null,
    age2 int  null,
    age3 int  null,
    age4 int  null,
    age5 int  null,
    gender1 text  null,
    gender2 text  null,
    gender3 text null,
    gender4 text null,
    gender5 text null,
    year1 text  null,
    year2 text  null,
    year3 text null,
    year4 text null,
    year5 text null,
    phys1 int  null,
    phys2 int  null,
    phys3 int null,
    phys4 int null,
    phys5 int null,    
    physRate1 int  null,
    physRate2 int  null,
    physRate3 int null,
    physRate4 int null,
    physRate5 int null,
    sciRate1 int  null,
    sciRate2 int  null,
    sciRate3 int null,
    sciRate4 int null,
    sciRate5 int null,
    sciWords1 int  null,
    sciWords2 int  null,
    sciWords3 int null,
    sciWords4 int null,
    sciWords5 int null
);
